# Generated by Django 4.2 on 2024-10-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userid',
            field=models.CharField(default='', max_length=6),
        ),
    ]
